### ISSUE TITLE
Repo público?

### ISSUE THREAD

**Issue by Lupama2** [sobluc/cliques_network#1]
Che Lucas, no te conviene poner el repo de tu tesis en privado? Solo por las dudas. SI alguien busca en GitHub "Cliques" le va a aparecer tu repo al toque y te puede copiar todo

**Comment by sobluc** [comment]
la idea es tenerlo como portfolio.

Si quieren usarlo que lo usen. O a que te referis con "copiar"?

**Comment by sobluc** [comment]
ya esta en proceso de revision

**Comment by Lupama2** [comment]
Oaaaaaa

**Comment by sobluc** [comment]
Igual de vuelta, lo tengo como portfolio para la industria

**Comment by sobluc** [comment]
falta comentarlo bien

**Comment by Lupama2** [comment]
Claro claro
